feat: add duration metrics for collectors
prometheus-community/elasticsearch_exporter pull request #424
Opened 2021-06-01 15:51 UTC by sysadmind

adds metrics to capture duration of time spent collecting metrics for:
  - cluster_health
  - clustersettings
  - index_stats
  - node_stats
  - snapshot_stats

this feature was adapted from the caarlos0/elasticsearch_exporter repo.

There seem to be a lot of metrics missing from the README, so I just added the metrics that this PR addresses, but I want to ensure that all metrics are in the README in a future PR.

2021-06-07 11:57 UTC, SuperQ commented
Hmm, typically we add this kind of thing as a gauge. For example in the node_exporter, [this is how we handle it](https://github.com/prometheus/node_exporter/blob/5b13775dc868e6c30a2346a8885fcf067c7aad57/collector/collector.go#L176).

2021-06-09 12:52 UTC, caarlos0 commented on collector/snapshots.go
> +			Help: "Duration spent in ElasticSearch snapshots scrape.",
Maybe "Time spent" sounds better? 🤔

2021-06-09 12:53 UTC, caarlos0 approved these changes

2021-06-09 14:02 UTC, SuperQ commented on collector/snapshots.go
> +			Help: "Duration spent in ElasticSearch snapshots scrape.",
I like "Time spent" as well.

2021-06-09 14:05 UTC, SuperQ commented on collector/cluster_health.go
> +			Name: prometheus.BuildFQName(namespace, subsystem, "scrape_duration_seconds"),
Hmm, maybe we should flip these per-subsystem metrics around and make them global, and use a label.

Maybe we do this in a refactor before cutting a new release? Although, we should not merge this until we cut a "safe harbor" release.

2021-06-09 14:06 UTC, SuperQ approved these changes
LGTM. I like the metric, but the whole per-collector metric naming stuff needs refactoring.

2021-08-19 13:00 UTC, LaurentDumont commented
Curious in this one too. I'd like to see if we have a performance issues with queries and it's a bit hard to see right now.

2022-01-19 11:04 UTC, SuperQ requested changes
Ping, this has some comments to address.

2022-07-28 08:47 UTC, SuperQ commented
This needs a rebase.

2024-03-01 17:17 UTC, smowky commented
this metrics might be really useful, any chance this PR will get processed?

2025-02-21 01:45 UTC, closed without merging