number_of_replicas
prometheus-community/elasticsearch_exporter pull request #483
Opened 2021-10-18 12:26 UTC by mac2000

motivation: hunting for indices with `number_of_replicas` being set to zero, which might cause data loss in certain scenarios, need this metric to configure alert

output will be:

```
# HELP elasticsearch_indices_settings_number_of_replicas index setting number_of_replicas
# TYPE elasticsearch_indices_settings_number_of_replicas gauge
elasticsearch_indices_settings_number_of_replicas{index="foo"} 3
elasticsearch_indices_settings_number_of_replicas{index="bar"} 0
```

closes #482

2022-01-19 11:08 UTC, SuperQ requested changes
Minor nit, otherwise LGTM.

2022-01-19 11:08 UTC, SuperQ commented on collector/indices_settings.go
> +					prometheus.BuildFQName(namespace, "indices_settings", "number_of_replicas"),
"number_of" is redundant. We can simplify this.

```suggestion
					prometheus.BuildFQName(namespace, "indices_settings", "replicas"),
```

2022-01-26 17:06 UTC, mac2000 commented
sorry for a noob question but seems like I have stuck with this DCO whatever, is there a chance you can press the button or should I figure out how to fix this check?

2022-08-04 15:35 UTC, rccrdpccl commented
Any chance we can get this merged @SuperQ ? I would love to have this metric exported

2022-08-04 21:21 UTC, SuperQ commented
This needs a DCO sign-off. You can use `git commit -s --amend` to add it.

2022-08-05 05:58 UTC, mac2000 commented
@SuperQ thank you, seems like it did the trick

2022-08-08 14:57 UTC, sysadmind requested changes
The README missed the update of the metric name.

2022-08-08 14:57 UTC, sysadmind commented on README.md
> +| elasticsearch_indices_settings_number_of_replicas                     | gauge     |             | Index setting value for index.number_of_replicas
```suggestion
| elasticsearch_indices_settings_replicas                     | gauge     |             | Index setting value for index.replicas
```

2022-10-24 10:28 UTC, mac2000 commented
@SuperQ  @sysadmind is there any chance it will be merged somewhere in the future or should something else be done?

2022-11-01 00:46 UTC, sysadmind approved these changes

2022-11-01 00:47 UTC, merged

2022-11-01 00:47 UTC, sysadmind commented
LGTM. Thanks!