Add elasticsearch_jvm_uptime gauge
prometheus-community/elasticsearch_exporter pull request #537
Opened 2022-03-01 09:33 UTC by perlun

I discovered that the the JVM uptime (readily available in the http://localhost:9200/_nodes/stats output) wasn't included in the output returned by the exporter. This PR adds it.

Tested locally with an ES 7.10.2 instance.

2022-03-15 08:08 UTC, perlun commented
Ping @sysadmind, would you min reviewing this? (unsure about what the process is in this repo, it seems to have a number of open PRs at the moment)

2022-04-06 23:43 UTC, sysadmind requested changes

2022-04-06 23:43 UTC, sysadmind commented on collector/nodes.go
> +					prometheus.BuildFQName(namespace, "jvm", "uptime"),
This should have the `_seconds` suffix to match prometheus naming standards https://prometheus.io/docs/practices/naming/

2022-04-13 14:43 UTC, merged

2022-04-14 06:49 UTC, perlun commented
Thanks for the merge @sysadmind. :pray: I intended to ping you that I had fixed & rebased this, but you seem to have noticed it anyway. :slightly_smiling_face: :+1: