Add https to metrics server
prometheus-community/elasticsearch_exporter pull request #615
Opened 2022-08-23 13:40 UTC by yuriykis

2022-08-24 23:22 UTC, sysadmind requested changes
Just a small adjustment to the kingpin flags. Otherwise good. Thanks!

2022-08-24 23:22 UTC, sysadmind commented on tls-config.yml
> +tls_server_config:
I don't think that this file is necessary.

2022-08-24 23:22 UTC, sysadmind commented on main.go
> +		tlsConfigFile = kingpin.Flag("web.config", "Path to config yaml file that can enable TLS").Default("").String()
This should be handled by the kingpinflag module from the exporter-toolkit.
`webflag "github.com/prometheus/exporter-toolkit/web/kingpinflag"`

```suggestion
		webConfig = webflag.AddFlags(kingpin.CommandLine)
```

2022-08-24 23:22 UTC, sysadmind commented on main.go
> +		if err := web.ListenAndServe(server, *tlsConfigFile, logger); err != nil {
```suggestion
		if err := web.ListenAndServe(server, *webConfig, logger); err != nil {
```

2022-08-25 11:45 UTC, yuriykis reviewed
Yes, the requested changes look good to me :)

2022-08-25 12:33 UTC, sysadmind approved these changes
LGTM. Thanks

2022-08-25 12:47 UTC, merged