Fix index field count
prometheus-community/elasticsearch_exporter pull request #675
Opened 2023-01-21 02:09 UTC by hartfordfive

This change applies a small modification that adds 1 to the field count prior to recursively counting the other nested fields in the mapping. (Issue #674)

2023-01-21 19:06 UTC, sysadmind requested changes
You're missing the DCO. The check has instructions for how to fix. 
I'm not sure this takes into account a situation where both type and properties are set. I'm not sure if these are mutually exclusive, but if not these would potentially double count those fields.

2023-01-21 19:06 UTC, sysadmind commented on CHANGELOG.md
> +## 1.5.1 / 2022-07-29
Version gets changed when we are ready for a release. 
```suggestion
## master / unreleased
```

2023-01-21 19:06 UTC, sysadmind commented on VERSION
> -1.5.0
This should not be changed.

2023-01-21 19:55 UTC, hartfordfive commented
@sysadmind , thank you for the quick feedback.   I will address those required changes you pointed out.   

As for counting a mapping where both type and property are set, although the type `object` could be technically be present with the `properties` field, it isn't usually defined explicitly (at least based on my experience) as that's the default value as per the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/object.html).
```
You are not required to set the field type to object explicitly, as this is the default value.
```
Having said that, the possibility is a valid edge case that should be accounted for, so I'll go ahead and make the modification.  Thank you for bringing that up.

2023-01-22 18:31 UTC, sysadmind approved these changes
LGTM Thanks!

2023-01-22 18:37 UTC, merged