Add missing documentation for ILM metrics
prometheus-community/elasticsearch_exporter pull request #892
Opened 2024-05-13 17:51 UTC by multani

#513 added the metrics but they were not documented.

I'm not sure about the "cardinality" content ; this is my understanding:

* `elasticsearch_ilm_status` has an `operation_mode` label which can have 3 values so I set cardinality to `3`
* `elasticsearch_ilm_index_status` has [more labels](https://github.com/prometheus-community/elasticsearch_exporter/blob/ea789710cea39aab5a7e96d64943cf7fbb903c4b/collector/ilm_indices.go#L59), in particular `index` which can be unbounded, so I didn't set any cardinality (since it depends on the number of indices in the cluster).

2024-12-14 16:16 UTC, sysadmind requested changes
Thanks for the PR, just a small cleanup to be consistent with the rest.

2024-12-14 16:16 UTC, sysadmind commented on README.md
> +| elasticsearch_ilm_status                                             | gauge      | 3           | Current status of ILM. Status can be `STOPPED`, `RUNNING`, `STOPPING`.
In this case, cardinality is the number of labels, not the number of possible values for the labels. ilm_status should be 1 and ilm_index_status should be 4.

2025-02-13 14:36 UTC, multani commented on README.md
> +| elasticsearch_ilm_status                                             | gauge      | 3           | Current status of ILM. Status can be `STOPPED`, `RUNNING`, `STOPPING`.
```suggestion
| elasticsearch_ilm_status                                             | gauge      | 1           | Current status of ILM. Status can be `STOPPED`, `RUNNING`, `STOPPING`.                              |
```

2025-02-13 14:36 UTC, multani commented on README.md
> +| elasticsearch_ilm_index_status                                       | gauge      |             | Status of ILM policy for index
```suggestion
| elasticsearch_ilm_index_status                                       | gauge      | 4           | Status of ILM policy for index                                                                      |
```

2025-02-15 16:36 UTC, sysadmind approved these changes

2025-02-15 16:38 UTC, merged